config/routes.rb
::Refinery::Application.routes.draw do

  resources :mailing_lists, :only => [:index] do
    collection do
      post :index
    end
  end

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :mailing_lists, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/mailing_list.rb
class MailingList < ActiveRecord::Base

  acts_as_indexed :fields => [:email]

  validates :email, :presence => true, :uniqueness => true
  
end

app/controllers/admin/mailing_lists_controller.rb
module Admin
  class MailingListsController < Admin::BaseController

    crudify :mailing_list,
            :title_attribute => 'email', :xhr_paging => true

  end
end

app/controllers/mailing_lists_controller.rb
class MailingListsController < ApplicationController

  before_filter :find_all_mailing_lists
  before_filter :find_page

  require 'net/http'

  GENERAL_MAILING_LIST_URL = 'http://lists.progressbar.sk/mailman/listinfo/general-discussion'
  GENERAL_MAILING_LIST_SUBSCRIBE_URL = 'http://lists.progressbar.sk/mailman/subscribe/general-discussion'
  GENERAL_MAILING_LIST_UNSUBSCRIBE_URL = 'http://lists.progressbar.sk/mailman/options/general-discussion'

  EVENTS_MAILING_LIST_URL = 'http://lists.progressbar.sk/mailman/listinfo/events'
  EVENTS_MAILING_LIST_SUBSCRIBE_URL = 'http://lists.progressbar.sk/mailman/subscribe/events'
  EVENTS_MAILING_LIST_UNSUBSCRIBE_URL = 'http://lists.progressbar.sk/mailman/options/events'

  def index
    flash[:success] = t('.events_mailinglist_subscription_success')
    subscriber = MailingList.find_by_email(@mailing_list[:email])
    # if subscriber not exits we create new and subcribe him where they want
    if subscriber.nil?
      if params[:mailing_list] && @mailing_list.valid?
        self.subscribe_to_general if @mailing_list.general
        self.subscribe_to_events if @mailing_list.events

        @mailing_list.save
        redirect_to :action => 'index'
      end
    else
      # otherwise we try subscribe or unsubscribe him from what they want
      if @mailing_list[:general]
        if subscriber[:general]
          subscriber.update_attributes(:general => false)
          redirect_to GENERAL_MAILING_LIST_UNSUBSCRIBE_URL
        else
          subscriber.update_attributes(:general => true) if self.subscribe_to_general
          redirect_to :action => 'index'
        end
      else
        if @mailing_list[:events]
          if subscriber[:events]
            subscriber.update_attributes(:events => false)
            redirect_to EVENTS_MAILING_LIST_UNSUBSCRIBE_URL
          else
            subscriber.update_attributes(:events => true) if self.subscribe_to_events
            redirect_to :action => 'index'
          end
        end
      end
    end
  end

  protected

  def subscribe_to_general
    gr = self.subscribe(GENERAL_MAILING_LIST_SUBSCRIBE_URL)
    if gr.code.to_i == 200
      flash[:success] = t('.general_mailinglist_subscription_success')
    else
      flash[:error] = t('.general_mailinglist_subscription_error')
    end
    gr.code.to_i == 200
  end

  def subscribe_to_events
    er = self.subscribe(EVENTS_MAILING_LIST_SUBSCRIBE_URL)
    if er.code.to_i == 200
      flash[:success] = t('.events_mailinglist_subscription_success')
    else
      flash[:error] = t('.events_mailinglist_subscription_error')
    end
    er.code.to_i == 200
  end

  def subscribe(url)
    url = URI.parse(url)
    post_args = {
      'email' => @mailing_list.email
    }

    Net::HTTP.post_form(url, post_args)
  end

  def find_all_mailing_lists
    @mailing_lists = MailingList.order('position ASC')
  end

  def find_page
    @page = Page.where(:link_url => "/mailing_lists").first
  end
end

app/views/admin/mailing_lists/_actions.html.erb
<ul>
  <% if Admin::MailingListsController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_mailing_lists_path
                  } %>
    </li>
  <% end %>

</ul>

app/views/admin/mailing_lists/_form.html.erb
<%= form_for [:admin, @mailing_list] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @mailing_list,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :email -%>
    <%= f.text_field :email, :class => 'larger widest'  -%>
  </div>
  
  <div class='field'>
    <%= f.label :general -%>
    <%= f.check_box :general, :checked => @mailing_list[:general]  -%>
  </div>
  
  <div class='field'>
    <%= f.label :events -%>
    <%= f.check_box :events, :checked => @mailing_list[:events]  -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.mailing_lists.mailing_list'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @mailing_list.email)
              } %>
<% end -%>

app/views/admin/mailing_lists/_mailing_list.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(mailing_list) -%>">
  <span class='title'>
    <%= mailing_list.email %>
  </span>
</li>

app/views/admin/mailing_lists/_mailing_lists.html.erb
<%= will_paginate @mailing_lists %>
<%= render :partial => "sortable_list" %>

app/views/admin/mailing_lists/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @mailing_lists.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'mailing_lists' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/mailing_lists/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'mailing_list', :collection => @mailing_lists %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/mailing_lists/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/mailing_lists/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::MailingListsController.sortable? and MailingList.count > 1 %>

app/views/admin/mailing_lists/new.html.erb
<%= render :partial => "form" %>

app/views/mailing_lists/_form.html.erb
<%= form_for @mailing_list do |f| %>
  <% unless @mailing_list.errors.blank? %>
    <div class="form-error">
      <% @mailing_list.errors.each do |elm, msg| %>
        <p><%= t(elm.to_s) %> <%= msg %></p>
      <% end %>
    </div>
  <% end %>
  <p>
    <%= f.check_box :general %>
    <%= f.label :general, t('.general_type'), :class => '' %>
    <br />
    <%= f.check_box :events %>
    <%= f.label :events, t('.events_type'), :class => '' %>
  </p>
  <div class="field">
    <%= f.label :email, t('.put_email'), :class => 'placeholder-fallback required' %>
    <%= f.email_field :email, :placeholder => t('.put_email'), :required => 'required', :class => 'required email text' %><%= f.submit t('.sign_in') %>
  </div>
  <p class="msg info">
    <img alt="info icon" src="/images/s.gif" class="ui-icon ui-icon-info" />
    <%= t('.info_privacy') %>
    <br /><br />
    <%= t('.info_logout') %>
  </p>      
<% end %>

app/views/mailing_lists/index.html.erb
<%= render :partial => "/shared/content_page" %>

app/views/mailing_lists/show.html.erb
<% content_for :body_content_title do %>
  <%= @mailing_list.email %>
<% end %>

<% content_for :body_content_left do %>
  <section>
    <h1>Email</h1>
    <p>
      <%=raw @mailing_list.email %>
    </p>
  </section>
  <section>
    <h1>General</h1>
    <p>
      <%=raw @mailing_list.general %>
    </p>
  </section>
  <section>
    <h1>Events</h1>
    <p>
      <%=raw @mailing_list.events %>
    </p>
  </section>
<% end %>

<% content_for :body_content_right do %>
  <aside>
    <h2><%= t('.other') %></h2>
    <ul id="mailing_lists">
      <% @mailing_lists.each do |mailing_list| %>
        <li>
          <%= link_to mailing_list.email, mailing_list_path(mailing_list) %>
        </li>
      <% end %>
    </ul>
  </aside>
<% end %>

<%= render :partial => "/shared/content_page" %>